window.TEAM_MEMBERS = [
  {
    slug: 'dr-erdem-ozturk',
    name: 'Dr Erdem Ozturk',
    role: 'Founder & CEO',
    group: 'Leadership',
    photo: 'assets/team-photos/dr-erdem-ozturk.png',
    linkedin: 'https://www.linkedin.com/in/erdemozturk/',
    bio: 'Internationally recognised digital machining leader with 20+ years in machining dynamics research, AMRC programme leadership, and commercially applied process optimisation.',
  },
  {
    slug: 'dr-huseyin-celikag',
    name: 'Dr Huseyin Celikag',
    role: 'CTO & Co-founder',
    group: 'Leadership',
    photo: 'assets/team-photos/dr-huseyin-celikag.png',
    linkedin: '',
    bio: 'Mechanical engineer with a PhD in robotic machining dynamics. Leads software development, machining process modelling, analysis, and optimisation.',
  },
  {
    slug: 'kate-woods',
    name: 'Kate Woods',
    role: 'Financial Director',
    group: 'Leadership',
    photo: 'assets/team-photos/kate-woods.png',
    linkedin: '',
    bio: 'Chartered Accountant trained at PwC with senior finance leadership experience across engineering, space, manufacturing, retail, publishing, and scaling SMEs.',
  },
  {
    slug: 'dr-luke-mason',
    name: 'Dr Luke Mason',
    role: 'Chief Software Architect',
    group: 'Leadership',
    photo: 'assets/team-photos/dr-luke-mason.png',
    linkedin: '',
    bio: 'Digital product and software architecture specialist across high-performance computing, cloud technologies, and advanced machining software delivery.',
  },
  {
    slug: 'cristina-sesma',
    name: 'Cristina Sesma',
    role: 'Head of Partnerships & Customer Success',
    group: 'Commercial',
    photo: 'assets/team-photos/cristina-sesma.png',
    linkedin: 'https://uk.linkedin.com/in/cristina-sesma',
    bio: 'International marketing, partnerships, and digital communications leader with 20+ years in high-tech engineering, additive manufacturing, and CNC markets.',
  },
  {
    slug: 'matthew-scherba',
    name: 'Matthew Scherba',
    role: 'Non-Executive Director',
    group: 'Board',
    photo: 'assets/team-photos/matthew-scherba.png',
    linkedin: '',
    bio: 'London-based entrepreneur and VC supporting AI, IoT, and deeptech companies with global growth, funding, product strategy, and exit experience.',
  },
  {
    slug: 'dr-mateo-leco',
    name: 'Dr Mateo Leco',
    role: 'Head of Data Science',
    group: 'Engineering',
    photo: 'assets/team-photos/dr-mateo-leco.png',
    linkedin: '',
    bio: 'Data-driven robotic machining specialist combining research and industrial experience in machine learning and AI for manufacturing applications.',
  },
  {
    slug: 'sally-clark',
    name: 'Sally Clark',
    role: 'Resourcing Business Partner',
    group: 'People',
    photo: 'assets/team-photos/sally-clark.png',
    linkedin: '',
    bio: 'Resourcing professional with nearly two decades building high-performing teams across engineering, manufacturing, and technology sectors.',
  },
  {
    slug: 'mustafa-gokturk-yandim',
    name: 'Mustafa Gokturk Yandim',
    role: 'Software Developer',
    group: 'Engineering',
    photo: 'assets/team-photos/mustafa-gokturk-yandim.png',
    linkedin: '',
    bio: 'Mechatronics and computer science engineer focused on software development and optimisation for Productive Machines products.',
  },
  {
    slug: 'dr-hamid-jamshidi',
    name: 'Dr Hamid Jamshidi',
    role: 'Machining Physics Developer',
    group: 'Engineering',
    photo: 'assets/team-photos/dr-hamid-jamshidi.png',
    linkedin: '',
    bio: 'Manufacturing engineer with research experience in super abrasive machining, precision milling models, dynamics, temperature, and thermal damage.',
  },
  {
    slug: 'arvind-anandhanarayanan',
    name: 'Arvind Anandhanarayanan',
    role: 'Software Developer',
    group: 'Engineering',
    photo: 'assets/team-photos/arvind-anandhanarayanan.png',
    linkedin: '',
    bio: 'Computer engineer with AI/ML, NLP, low-level systems, parallelisation, GPU, and cloud computing experience.',
  },
  {
    slug: 'baris-guzel',
    name: 'Baris Guzel',
    role: 'Software Developer',
    group: 'Engineering',
    photo: 'assets/team-photos/baris-guzel.png',
    linkedin: '',
    bio: 'Electrical and electronics engineer focused on CAD/CAM plug-ins, embedded systems, computer architecture, and high-performance software.',
  },
  {
    slug: 'arman-zonuzi',
    name: 'Arman Zonuzi',
    role: 'Machining Physics Developer',
    group: 'Engineering',
    photo: 'assets/team-photos/arman-zonuzi.png',
    linkedin: '',
    bio: 'Advanced manufacturing researcher with experience in micromilling force modelling, machining dynamics, robotic decommissioning, and milling distortion analysis.',
  },
  {
    slug: 'dr-mate-toth',
    name: 'Dr Mate Toth',
    role: 'Machining Physics Developer',
    group: 'Engineering',
    photo: 'assets/team-photos/dr-mate-toth.png',
    linkedin: '',
    bio: 'Mechanical engineer specialising in vibration analysis, chatter suppression, turning, milling, grinding, machining process modelling, and optimisation.',
  },
]
